#! /bin/sh

set -eu

cd "$(dirname "$0")"

die () {
    echo "$@"
    exit 1
}

wait_for_file () {
    for _ in $(seq 20); do
	if [ -f tmp.out ] ; then
	    return
	fi
	sleep 1
    done
    exit 1
}

rm -f tmp.agent tmp.out tmp.key tmp.key.pub

ssh-keygen -q -N '' -t ed25519 -f tmp.key

# Can't use go run, since that process appears to keep stdout open.
go build -o tmp.agent ../cmd/sigsum-agent

PID_BY_AGENT=$(./tmp.agent --pid-file - -k tmp.key \
   /bin/sh -c 'echo $$ > tmp.out ; sleep 1000' 2> tmp.stderr &)

wait_for_file tmp.out

PID_BY_SH="$(cat tmp.out)"
[ "${PID_BY_SH}" = "${PID_BY_AGENT}" ] || die "unexpected pid file contents: ${PID_BY_AGENT}"

kill -HUP "${PID_BY_AGENT}"
wait

grep -q -i hangup tmp.stderr || die 'no log message indicating hangup signal'
