#! /bin/sh

set -e

cd "$(dirname "$0")"

rm -f tmp.*

go run ../cmd/genkey-mldsa44 -o tmp.key >/dev/null
fp=$(go run ../cmd/genkey-mldsa44 -l tmp.key)
[ -n "$fp" ]

go run ../cmd/sigsum-agent -k tmp.key \
  go run ./signverify-mldsa "$fp" "the only winning move is not to play $$"
