#!/bin/bash

###
# Labels of objects that we have
###
export BACKUP_AUTH_LABEL="Backup authentication"   # Can do everything
export LOGSRV_AUTH_LABEL="Logsrv authentication"   # Just Ed25519 signing
export WITNESS_AUTH_LABEL="Witness authentication" # Just Ed25519 signing
export WRAPPING_KEY_LABEL="Common wrap key"        # Just Ed25519 import/export

export LOGSRV_SIGNING_KEY_LABEL="Log server signing key"
export WITNESS_SIGNING_KEY_LABEL="Witness signing key"

###
# Arbitrary object IDs that we choose (16-bit number)
###
export BACKUP_AUTH_ID=100
export LOGSRV_AUTH_ID=200
export WITNESS_AUTH_ID=300
export WRAPPING_KEY_ID=400

export LOGSRV_SIGNING_KEY_ID=500
export WITNESS_SIGNING_KEY_ID=600

###
# Arbitrary domain that we choose to put signing keys in (1-16)
###
export LOGSRV_SIGNING_DOMAIN=10
export WITNESS_SIGNING_DOMAIN=11
