#!/bin/bash

set -eu

cd "$(dirname "$0")"
. config # loads constants for YubiHSM object IDs and such
. common # gain access to a few helpers
trap clean_up EXIT

###
# Read from backup
###
id=$(yubihsm_probe "to create a backup replica from")
[[ -z "$authkey_passphrase" ]] && read -rp "ENTER authkey passphrase: " authkey_passphrase
[[ -z "$wrapkey_passphrase" ]] && read -rp "ENTER wrapkey passphrase: " wrapkey_passphrase

yubihsm_shell << EOF
    connect
    session open "$BACKUP_AUTH_ID" "$authkey_passphrase"

    get     wrapped 0 "$WRAPPING_KEY_ID" asymmetric-key "$LOGSRV_SIGNING_KEY_ID"  "$wrap_file_log"
    get     wrapped 0 "$WRAPPING_KEY_ID" asymmetric-key "$WITNESS_SIGNING_KEY_ID" "$wrap_file_witness"

    session close   0
EOF

###
# Prepare backup replica
###
id=$(yubihsm_probe "to provision new backup replica onto (must be in factory-reset state)")
yubihsm_shell << EOF
    connect
    session open 1 password

    put     authkey 0 "$BACKUP_AUTH_ID"  "$BACKUP_AUTH_LABEL"  all all                           all                              "$authkey_passphrase"
    put     wrapkey 0 "$WRAPPING_KEY_ID" "$WRAPPING_KEY_LABEL" all import-wrapped,export-wrapped exportable-under-wrap,sign-eddsa "$wrapkey_passphrase"
    put     wrapped 0 "$WRAPPING_KEY_ID" "$wrap_file_log"
    put     wrapped 0 "$WRAPPING_KEY_ID" "$wrap_file_witness"

    delete 0 1 authentication-key

    list    objects 0
    session close   0
EOF

echo "backup_authkey_passphrase=$authkey_passphrase"
echo "backup_wrapkey_passphrase=$wrapkey_passphrase"
echo "backup_serial_number=$id"
