#!/bin/bash

set -eu

cd "$(dirname "$0")"
. ./config # loads constants for YubiHSM object IDs and such
. ./common # gain access to a few helpers
trap clean_up EXIT

###
# Read from backup
###
id=$(yubihsm_probe "to import 3x additional witness keys from")
[[ -z "$authkey_passphrase" ]] && read -rp "ENTER authkey passphrase: " authkey_passphrase

compability1=""
compability2=""
if version_gt "$yubihsm_version" "2.5.0"; then
  compability1=0
  compability2=asymmetric-key
fi

yubihsm_shell << EOF
    connect
    session open "$BACKUP_AUTH_ID" "$authkey_passphrase"

    get     wrapped 0 "$WRAPPING_KEY_ID" asymmetric-key "$WITNESS_SIGNING_KEY_ID_G1" $compability1 "${wrap_file_witness}.g1"
    get     wrapped 0 "$WRAPPING_KEY_ID" asymmetric-key "$WITNESS_SIGNING_KEY_ID_G2" $compability1 "${wrap_file_witness}.g2"
    get     wrapped 0 "$WRAPPING_KEY_ID" asymmetric-key "$WITNESS_SIGNING_KEY_ID_G3" $compability1 "${wrap_file_witness}.g3"

    session close   0
EOF

###
# Prepare backup replica
###
id=$(yubihsm_probe "to sync 3x additional witness keys to")
yubihsm_shell << EOF
    connect
    session open "$BACKUP_AUTH_ID" "$authkey_passphrase"

    put wrapped 0 "$WRAPPING_KEY_ID" "${wrap_file_witness}.g1"
    put wrapped 0 "$WRAPPING_KEY_ID" "${wrap_file_witness}.g2"
    put wrapped 0 "$WRAPPING_KEY_ID" "${wrap_file_witness}.g3"

    get pubkey 0 "$LOGSRV_SIGNING_KEY_ID" $compability2 "$log_pubkey_file"
    get pubkey 0 "$WITNESS_SIGNING_KEY_ID" $compability2 "$witness_pubkey_file"

    sign eddsa 0 "$LOGSRV_SIGNING_KEY_ID"  ed25519 "$message_file" "$log_signature_file"
    sign eddsa 0 "$WITNESS_SIGNING_KEY_ID" ed25519 "$message_file" "$witness_signature_file"

    get pubkey 0 "$WITNESS_SIGNING_KEY_ID_G1" $compability2 "${witness_pubkey_file}.g1"
    get pubkey 0 "$WITNESS_SIGNING_KEY_ID_G2" $compability2 "${witness_pubkey_file}.g2"
    get pubkey 0 "$WITNESS_SIGNING_KEY_ID_G3" $compability2 "${witness_pubkey_file}.g3"

    sign eddsa 0 "$WITNESS_SIGNING_KEY_ID_G1" ed25519 "$message_file" "${witness_signature_file}.g1"
    sign eddsa 0 "$WITNESS_SIGNING_KEY_ID_G2" ed25519 "$message_file" "${witness_signature_file}.g2"
    sign eddsa 0 "$WITNESS_SIGNING_KEY_ID_G3" ed25519 "$message_file" "${witness_signature_file}.g3"

    list    objects 0
    session close   0
EOF

openssl pkeyutl -verify -pubin -inkey "$log_pubkey_file"     -sigfile <(base64 -d "$log_signature_file")     -rawin -in "$message_file" >&2
openssl pkeyutl -verify -pubin -inkey "$witness_pubkey_file" -sigfile <(base64 -d "$witness_signature_file") -rawin -in "$message_file" >&2

openssl pkeyutl -verify -pubin -inkey "${witness_pubkey_file}.g1" -sigfile <(base64 -d "${witness_signature_file}.g1") -rawin -in "$message_file" >&2
openssl pkeyutl -verify -pubin -inkey "${witness_pubkey_file}.g2" -sigfile <(base64 -d "${witness_signature_file}.g2") -rawin -in "$message_file" >&2
openssl pkeyutl -verify -pubin -inkey "${witness_pubkey_file}.g3" -sigfile <(base64 -d "${witness_signature_file}.g3") -rawin -in "$message_file" >&2

echo "backup_serial_number=$id"
echo ""

echo "logsrv =>"
cat "$log_pubkey_file"
echo ""

echo "witness =>"
cat "$witness_pubkey_file"
echo ""

echo "witness G1 =>"; cat "${witness_pubkey_file}.g1"; echo ""
echo "witness G2 =>"; cat "${witness_pubkey_file}.g2"; echo ""
echo "witness G3 =>"; cat "${witness_pubkey_file}.g3"
