#!/bin/bash

#
# Intended usage: extend an already provisioned backup YubiHSM with 3 additional
# witnesses keys that are generated on the YubiHSM by this script.
#
# Note: it is not possible to overwrite existing keys without first deleting
# them explicitly.  So, as long as we don't do deletions this is very safe.
# That said, it is better to be safe than sorry so doublecheck that the old
# logsrv and witness keys are *still* being printed without modificaiton.
#

set -eu

cd "$(dirname "$0")"
. ./config # loads constants for YubiHSM object IDs and such
. ./common # loads helpers and reads environment variables
trap clean_up EXIT

###
# Generate keys to provision first backup
###
id=$(yubihsm_probe "for keygen of 3x additional witness keys")
[[ -z "$authkey_passphrase" ]] && read -rp "ENTER authkey passphrase: " authkey_passphrase

compability=""
if version_gt "$yubihsm_version" "2.5.0"; then
  compability=asymmetric-key
fi

echo "" # identical output formatting as yhp-backup
yubihsm_shell << EOF
	connect
	session open "$BACKUP_AUTH_ID" "$authkey_passphrase"

	generate asymmetric 0 "$WITNESS_SIGNING_KEY_ID_G1" "$WITNESS_SIGNING_KEY_LABEL G1" "$WITNESS_SIGNING_DOMAIN" exportable-under-wrap,sign-eddsa ed25519
	generate asymmetric 0 "$WITNESS_SIGNING_KEY_ID_G2" "$WITNESS_SIGNING_KEY_LABEL G2" "$WITNESS_SIGNING_DOMAIN" exportable-under-wrap,sign-eddsa ed25519
	generate asymmetric 0 "$WITNESS_SIGNING_KEY_ID_G3" "$WITNESS_SIGNING_KEY_LABEL G3" "$WITNESS_SIGNING_DOMAIN" exportable-under-wrap,sign-eddsa ed25519

	get pubkey 0 "$LOGSRV_SIGNING_KEY_ID" $compability "$log_pubkey_file"
	get pubkey 0 "$WITNESS_SIGNING_KEY_ID" $compability "$witness_pubkey_file"

	sign eddsa 0 "$LOGSRV_SIGNING_KEY_ID"  ed25519 "$message_file" "$log_signature_file"
	sign eddsa 0 "$WITNESS_SIGNING_KEY_ID" ed25519 "$message_file" "$witness_signature_file"

	get pubkey 0 "$WITNESS_SIGNING_KEY_ID_G1" $compability "${witness_pubkey_file}.g1"
	get pubkey 0 "$WITNESS_SIGNING_KEY_ID_G2" $compability "${witness_pubkey_file}.g2"
	get pubkey 0 "$WITNESS_SIGNING_KEY_ID_G3" $compability "${witness_pubkey_file}.g3"

	sign eddsa 0 "$WITNESS_SIGNING_KEY_ID_G1" ed25519 "$message_file" "${witness_signature_file}.g1"
	sign eddsa 0 "$WITNESS_SIGNING_KEY_ID_G2" ed25519 "$message_file" "${witness_signature_file}.g2"
	sign eddsa 0 "$WITNESS_SIGNING_KEY_ID_G3" ed25519 "$message_file" "${witness_signature_file}.g3"

	list     objects    0
	session  close      0
EOF

openssl pkeyutl -verify -pubin -inkey "$log_pubkey_file"     -sigfile <(base64 -d "$log_signature_file")     -rawin -in "$message_file" >&2
openssl pkeyutl -verify -pubin -inkey "$witness_pubkey_file" -sigfile <(base64 -d "$witness_signature_file") -rawin -in "$message_file" >&2

openssl pkeyutl -verify -pubin -inkey "${witness_pubkey_file}.g1" -sigfile <(base64 -d "${witness_signature_file}.g1") -rawin -in "$message_file" >&2
openssl pkeyutl -verify -pubin -inkey "${witness_pubkey_file}.g2" -sigfile <(base64 -d "${witness_signature_file}.g2") -rawin -in "$message_file" >&2
openssl pkeyutl -verify -pubin -inkey "${witness_pubkey_file}.g3" -sigfile <(base64 -d "${witness_signature_file}.g3") -rawin -in "$message_file" >&2

echo "backup_serial_number=$id"
echo ""

echo "logsrv =>"
cat "$log_pubkey_file"
echo ""

echo "witness =>"
cat "$witness_pubkey_file"
echo ""

echo "witness G1 =>"; cat "${witness_pubkey_file}.g1"; echo ""
echo "witness G2 =>"; cat "${witness_pubkey_file}.g2"; echo ""
echo "witness G3 =>"; cat "${witness_pubkey_file}.g3"
