#!/bin/bash

set -eu

cd "$(dirname "$0")"
. ./config # loads constants for YubiHSM object IDs and such
. ./common # loads helpers and reads environment variables
trap clean_up EXIT

compability1=""
compability2=""
if version_gt "$yubihsm_version" "2.5.0"; then
  compability1=0
  compability2=asymmetric-key
fi

###
# Read backup
###
yubihsm_probe "to restore witness signing key from" >/dev/null
[[ -z "$authkey_passphrase" ]] && read -rp "ENTER authkey passphrase: " authkey_passphrase
[[ -z "$wrapkey_passphrase" ]] && read -rp "ENTER wrapkey passphrase: " wrapkey_passphrase
witness_authkey_passphrase=$(yubihsm_get_passphrase "$BACKUP_AUTH_ID" "$authkey_passphrase")

[[ -z "$key_id" ]] && read -rp "ENTER witness signing key id: " key_id
yubihsm_shell << EOF
	connect
	session open      "$BACKUP_AUTH_ID"  "$authkey_passphrase"
	get     wrapped 0 "$WRAPPING_KEY_ID" asymmetric-key "$key_id" $compability1 "$wrap_file_witness"
	session close   0
EOF

###
# Prepare signing oracle
###
id=$(yubihsm_probe "to provision new witness signing oracle on (must be in factory-reset state)")

yubihsm_shell << EOF
	connect
	session open 1 password

	put     authkey 0 "$WITNESS_AUTH_ID" "$WITNESS_AUTH_LABEL" "$WITNESS_SIGNING_DOMAIN" sign-eddsa none "$witness_authkey_passphrase"
	put     wrapkey 0 "$WRAPPING_KEY_ID" "$WRAPPING_KEY_LABEL" "$WITNESS_SIGNING_DOMAIN" import-wrapped,export-wrapped exportable-under-wrap,sign-eddsa "$wrapkey_passphrase"
	put     wrapped 0 "$WRAPPING_KEY_ID" "$wrap_file_witness"

	get pubkey 0 "$key_id" $compability2 "$witness_pubkey_file"
	sign eddsa 0 "$key_id" ed25519 "$message_file" "$witness_signature_file"

	put      authkey    0 "$WITNESS_AUTH_ID_TEST"        "$WITNESS_AUTH_LABEL TESTONLY"        "$WITNESS_SIGNING_DOMAIN_TEST" sign-eddsa none "12345678"
	generate asymmetric 0 "$WITNESS_SIGNING_KEY_ID_TEST" "$WITNESS_SIGNING_KEY_LABEL TESTONLY" "$WITNESS_SIGNING_DOMAIN_TEST" sign-eddsa ed25519

	get pubkey 0 "$WITNESS_SIGNING_KEY_ID_TEST" $compability2 "${witness_pubkey_file}.test"
	sign eddsa 0 "$WITNESS_SIGNING_KEY_ID_TEST" ed25519 "$message_file" "${witness_signature_file}.test"

	delete          0 "$WRAPPING_KEY_ID" wrap-key
	delete          0 1                  authentication-key

	list    objects 0
	session close   0
EOF

openssl pkeyutl -verify -pubin -inkey "$witness_pubkey_file"        -sigfile <(base64 -d "$witness_signature_file")        -rawin -in "$message_file" >&2
openssl pkeyutl -verify -pubin -inkey "${witness_pubkey_file}.test" -sigfile <(base64 -d "${witness_signature_file}.test") -rawin -in "$message_file" >&2

echo "witness_authkey_passphrase=$witness_authkey_passphrase"
echo "witness_serial_number=$id"
echo "witness pubkey =>"
cat "$witness_pubkey_file"
echo ""
echo "test key =>"
cat "${witness_pubkey_file}.test"
