#!/bin/bash

set -eu

cd "$(dirname "$0")"
. config # loads constants for YubiHSM object IDs and such
. common # loads helpers and reads environment variables
trap clean_up EXIT

###
# Generate keys to provision first backup
###
id=$(yubihsm_probe "keygen and initial backup provisioning")
authkey_pass=$(yubihsm_get_passphrase 1 password)
wrapkey_pass=$(yubihsm_get_passphrase 1 password)

yubihsm_shell << EOF
	connect
	session open 1 password

	put      authkey    0 "$BACKUP_AUTH_ID"         "$BACKUP_AUTH_LABEL"         all                       all                              all                              "$authkey_pass"
	put      wrapkey    0 "$WRAPPING_KEY_ID"        "$WRAPPING_KEY_LABEL"        all                       import-wrapped,export-wrapped    exportable-under-wrap,sign-eddsa "$wrapkey_pass"
	generate asymmetric 0 "$LOGSRV_SIGNING_KEY_ID"  "$LOGSRV_SIGNING_KEY_LABEL"  "$LOGSRV_SIGNING_DOMAIN"  exportable-under-wrap,sign-eddsa ed25519
	generate asymmetric 0 "$WITNESS_SIGNING_KEY_ID" "$WITNESS_SIGNING_KEY_LABEL" "$WITNESS_SIGNING_DOMAIN" exportable-under-wrap,sign-eddsa ed25519

	delete 0 1 authentication-key

	list     objects    0
	session  close      0
EOF

echo "backup_authkey_passphrase=$authkey_pass"
echo "backup_wrapkey_passphrase=$wrapkey_pass"
echo "backup_id=$id"
