#!/bin/bash

set -eu

. config
. common

yubihsm_init "keygen and backup" 
backup_auth_pass=$(yubihsm_get_passphrase 1 password)
wrapping_key_pass=$(yubihsm_get_passphrase 1 password)
logsrv_auth_pass1=$(yubihsm_get_passphrase 1 password)
logsrv_auth_pass2=$(yubihsm_get_passphrase 1 password)
witness_auth_pass=$(yubihsm_get_passphrase 1 password)
yubihsm-shell << EOF
connect

session open    1 password
put     authkey 0 "$BACKUP_AUTH_ID" "$BACKUP_AUTH_LABEL" all all all "$backup_auth_pass"
session close   0

session open "$BACKUP_AUTH_ID" "$backup_auth_pass"
delete 0 1 authentication-key

generate asymmetric 0 "$LOGSRV_SIGNING_KEY_ID"  "$LOGSRV_SIGNING_KEY_LABEL"  "$LOGSRV_SIGNING_DOMAIN"  exportable-under-wrap,sign-eddsa ed25519
generate asymmetric 0 "$WITNESS_SIGNING_KEY_ID" "$WITNESS_SIGNING_KEY_LABEL" "$WITNESS_SIGNING_DOMAIN" exportable-under-wrap,sign-eddsa ed25519
put      wrapkey    0 "$WRAPPING_KEY_ID" "$WRAPPING_KEY_LABEL" all import-wrapped,export-wrapped exportable-under-wrap,sign-eddsa "$wrapping_key_pass"
get      wrapped    0 "$WRAPPING_KEY_ID" asymmetric-key "$LOGSRV_SIGNING_KEY_ID" "$WRAP_FILE_LOG"
get      wrapped    0 "$WRAPPING_KEY_ID" asymmetric-key "$WITNESS_SIGNING_KEY_ID" "$WRAP_FILE_WITNESS"

list    objects 0
session close   0
EOF
kill $pid

yubihsm_init "backup replica" 
yubihsm-shell << EOF
connect

session open    1 password
put     authkey 0 "$BACKUP_AUTH_ID" "$BACKUP_AUTH_LABEL" all all all "$backup_auth_pass"
session close   0

session open "$BACKUP_AUTH_ID" "$backup_auth_pass"
delete 0 1 authentication-key

put     wrapkey 0 "$WRAPPING_KEY_ID" "$WRAPPING_KEY_LABEL" all import-wrapped,export-wrapped exportable-under-wrap,sign-eddsa "$wrapping_key_pass"
put     wrapped 0 "$WRAPPING_KEY_ID" "$WRAP_FILE_LOG"
put     wrapped 0 "$WRAPPING_KEY_ID" "$WRAP_FILE_WITNESS"

list    objects 0
session close   0
EOF
kill $pid

yubihsm_init "logsrv signing oracle#1"
yubihsm-shell << EOF
connect

session open 1 password

put authkey 0 "$LOGSRV_AUTH_ID" "$LOGSRV_AUTH_LABEL" "$LOGSRV_SIGNING_DOMAIN" sign-eddsa none "$logsrv_auth_pass1"
put wrapkey 0 "$WRAPPING_KEY_ID" "$WRAPPING_KEY_LABEL" "$LOGSRV_SIGNING_DOMAIN" import-wrapped,export-wrapped exportable-under-wrap,sign-eddsa "$wrapping_key_pass"
put wrapped 0 "$WRAPPING_KEY_ID" "$WRAP_FILE_LOG"

delete 0 1 authentication-key
delete 0 "$WRAPPING_KEY_ID" wrap-key

list    objects 0
session close   0
EOF
kill $pid

yubihsm_init "logsrv signing oracle#2"
yubihsm-shell << EOF
connect

session open 1 password

put authkey 0 "$LOGSRV_AUTH_ID" "$LOGSRV_AUTH_LABEL"  "$LOGSRV_SIGNING_DOMAIN" sign-eddsa none "$logsrv_auth_pass2"
put wrapkey 0 "$WRAPPING_KEY_ID" "$WRAPPING_KEY_LABEL" "$LOGSRV_SIGNING_DOMAIN" import-wrapped,export-wrapped exportable-under-wrap,sign-eddsa "$wrapping_key_pass"
put wrapped 0 "$WRAPPING_KEY_ID" "$WRAP_FILE_LOG"

delete 0 1 authentication-key
delete 0 $WRAPPING_KEY_ID wrap-key

list    objects 0
session close   0
EOF
kill $pid

yubihsm_init "witness signing oracle"
yubihsm-shell << EOF
connect

session open 1 password

put authkey 0 "$WITNESS_AUTH_ID" "$WITNESS_AUTH_LABEL" "$WITNESS_SIGNING_DOMAIN" sign-eddsa none "$witness_auth_pass"
put wrapkey 0 "$WRAPPING_KEY_ID" "$WRAPPING_KEY_LABEL" "$WITNESS_SIGNING_DOMAIN" import-wrapped,export-wrapped exportable-under-wrap,sign-eddsa "$wrapping_key_pass"
put wrapped 0 "$WRAPPING_KEY_ID" "$WRAP_FILE_WITNESS"

delete 0 1 authentication-key
delete 0 $WRAPPING_KEY_ID wrap-key

list    objects 0
session close   0
EOF
kill $pid

info "DONE"
echo "Backup auth:   $backup_auth_pass"
echo "Logsrv auth#1: $logsrv_auth_pass1"
echo "Logsrv auth#2: $logsrv_auth_pass2"
echo "Witness auth:  $witness_auth_pass"
echo "Wrapping key:  $wrapping_key_pass"
