#!/bin/bash

#
# Install yubihsm-shell on branch pkcs11-3_0.
# See how the SSH-agent side of PKCS11 doesn't support Ed25519 yet:
#
#     [..snip...]
#     skipping unsupported key type
#     failed to fetch key
#     [..snip...]
#
# I.e., this error output is not from YubiHSM, see:
# https://github.com/openssh/openssh-portable/blob/master/ssh-pkcs11.c#L1272-L1290
#
# It works as expected to use an SSH-supported key type like p256, see below.
#

set -eu

. config
. common

yubihsm_init "test"
yubihsm-shell << EOF
connect

session open 1 password

generate asymmetric 0  9 "Logsrv key p256"    all all ecp256
generate asymmetric 0 10 "Logsrv key ed25519" all all ed25519

put authkey 0 2 "Logsrv auth" all all all aaaabbbbcccc
delete 0 1 authentication-key

list    objects 0
session close   0
EOF

cat << EOF > yubihsm_pkcs11.conf
connector=http://127.0.0.1:12345
debug-file = $(pwd)/yubihsm_pkcs11_debug.txt
debug
dinout
libdebug
EOF
export YUBIHSM_PKCS11_CONF="$(pwd)/yubihsm_pkcs11.conf"

info "Use YubiHSM password 0002aaaabbbbcccc"
info "See yubihsm_pkcs11_debug.txt for logs"

info "List keys with ssh-keygen"
ssh-keygen -D /usr/lib/x86_64-linux-gnu/pkcs11/yubihsm_pkcs11.so

info "Start SSH agent"
eval "$(ssh-agent -s)"

info "Add keys"
ssh-add -s /usr/lib/x86_64-linux-gnu/pkcs11/yubihsm_pkcs11.so

info "List keys"
ssh-add -l

kill $(pidof ssh-agent)
rm -f yubihsm_pkcs11.conf
read -rp "ENTER to delete yubihsm_pkcs11_debug.txt, ctrl+C to exit"
rm -f yubihsm_pkcs11_debug.txt
